import sqlite3
from tkinter import *
from tkinter import ttk 
connection=sqlite3.connect("hotel.db") 
cursor=connection.cursor() 
root=Tk() 
a=ttk.Label(root,text="Username") 
a.grid(row=0,column=0) 
b=ttk.Label(root,text="password") 
b.grid(row=1,column=0) 
a1=ttk.Label(root,text="Contact") 
a1.grid(row=2,column=0) 
b1=ttk.Label(root,text="Emas1") 
b1.grid(row=3,column=0) 
c=ttk.Entry(root) 
c.grid(row=0,column=1) 
d=ttk.Entry(root) 
d.grid(row=1,column=1) 
c1=ttk.Entry(root) 
c1.grid(row=2,column=1) 
d1=ttk.Entry(root) 
d1.grid(row=3,column=1) 
username=c.get() 
password=d.get() 
contact=c1.get() 
email=d1.get() 

root.mainloop()
#prInt(username) 
#print(password) 